# Generated by Django 5.0.1 on 2024-01-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department_mgnt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept',
            name='Dep_head',
            field=models.CharField(default='Alexa', max_length=50),
        ),
    ]
