# Generated by Django 5.0.1 on 2024-01-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department_mgnt', '0002_dept_dep_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept',
            name='Dep_head',
        ),
    ]
