# Generated by Django 5.0.1 on 2024-01-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department_mgnt', '0004_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='hierarchy',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Department_mgnt.dept'),
        ),
    ]
