# Generated by Django 5.0.1 on 2024-01-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Sal_23', models.CharField(max_length=50)),
                ('Sal_24', models.CharField(max_length=50)),
            ],
        ),
    ]
