# Generated by Django 5.0.1 on 2024-01-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary_mgnt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='Sal_23',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Sal_24',
            field=models.IntegerField(max_length=50),
        ),
    ]
