# Generated by Django 5.0.1 on 2024-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salary_mgnt', '0002_alter_salary_sal_23_alter_salary_sal_24'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='Sal_23',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='salary',
            name='Sal_24',
            field=models.IntegerField(),
        ),
    ]
